version: '2'

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        env_file: .env
        links: 
            - "node:node"
        volumes:
            - ./letsencrypt:/etc/letsencrypt
    node:
        build: ./node
        ports:
            - "3000"
    redis:
        image: redis
        ports:
            - "6379"
