version: '2'

services:
    nginx:
        build: ./nginx
        env_file: .env
        ports:
            - "80:80"
            - "443:443"
        links: 
            - "node:node"
        volumes:
            - ./letsencrypt:/etc/letsencrypt
    node:
        build: ./node
        env_file: .env
        ports:
            - "3000"
